import ctypes
from _typeshed import Incomplete
from typing import Callable

appkit: Incomplete
objc: Incomplete
void_p = ctypes.c_void_p
ull = ctypes.c_uint64
MSGPROTOTYPE: Incomplete
msg: Incomplete

def n(name): ...
def C(classname): ...
def theme() -> str: ...
def isDark() -> bool: ...
def isLight() -> bool: ...
def listener(callback: Callable[[str], None]) -> None: ...
